### ISSUE TITLE
Cannot integrate your example code to ASP.NET Core

### ISSUE THREAD

**Issue by fernandoagomezf** [microsoftgraph/aspnet-todo-rest-sample#4]
Hello everyone. I ran the example application and followed the steps described in the documentation, and the application ran well, I could see the graph explorer and performed some queries well enough. 

Now, I have an ASP.NET Core application with Work & School account login, as generated by the Visual Studio 2015 Update 3 wizard. I'm trying to integrate your example, but alas I can't. For instance, copying SessionTokenCache won't work, because of the usage of System.Web.dll, which for some reason I cannot reference in my project. 

I created my own version, but I'm not sure whether this will work as intended (see code at the end).

Do you have some guidelines as to how to run the example for ASP.NET Core? Or do you have some example in ASP.NET Core (I haven't been able to find one). 

Thanks in advance.  

```
public class SessionTokenCache
    : TokenCache
{
    private HttpContext context;
    private static readonly object FileLock = new object();
    private readonly string CacheId = string.Empty;
    public string UserObjectId = string.Empty;

    public SessionTokenCache(string userId, HttpContext context)
    {
        this.context = context;
        this.UserObjectId = userId;
        this.CacheId = UserObjectId + "_TokenCache";

        AfterAccess = AfterAccessNotification;
        BeforeAccess = BeforeAccessNotification;
        Load();
    }

    public void Load()
    {
        lock (FileLock) {
            Deserialize((byte[])context.Session.Get(CacheId));
        }
    }

    public void Persist()
    {
        lock (FileLock) {

            // Reflect changes in the persistent store.
            var bytes = Serialize();
            var x = System.Text.Encoding.UTF8.GetString(bytes);
            context.Session.Set(CacheId, Serialize());

            // After the write operation takes place, restore the HasStateChanged bit to false.
            HasStateChanged = false;
        }
    }

    public override void Clear(string clientId)
    {
        base.Clear(clientId);
        context.Session.Remove(CacheId);
    }

    // Triggered right before MSAL needs to access the cache.
    // Reload the cache from the persistent store in case it changed since the last access.
    private void BeforeAccessNotification(TokenCacheNotificationArgs args)
    {
        Load();
    }

    // Triggered right after MSAL accessed the cache.
    private void AfterAccessNotification(TokenCacheNotificationArgs args)
    {
        // if the access operation resulted in a cache update
        if (HasStateChanged) {
            Persist();
        }
    }
}
```

**Comment by DianeD** [comment]
Hi @fernandoagomezf . Thanks for the feedback! ASP.NET Core doesn't use System.Web, but it looks like similar functionality is available in **Microsoft.AspNetCore**.

Can you take a look at this Azure AD sample and see if it might work for your scenario? 
[active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore ](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/blob/master/WebApp-WebAPI-OpenIdConnect-DotNet/Utils/NaiveSessionCache.cs)

**Comment by DianeD** [comment]
Hi @fernandoagomezf . Closing this issue. Please reopen if you're still having problems. Thanks!
