### ISSUE TITLE
work with Excel file using sharepoint document library

### ISSUE THREAD

**Issue by ravianand1988** [microsoftgraph/aspnet-todo-rest-sample#5]
I downloaded and customized this project. this is working fine without any issue with onedrive excel files/items. but i have to do this using office 365 sharepoint online only. which is not working. 
i am able to get file id using service point as follows:
`  var serviceEndpoint = "https://graph.microsoft.com/beta/sites/mydomain.sharepoint.com:/foa/bd:/lists/Budget/items";`

but i am not sure how should i define workbook end point url with sharepoint to update/manipulate same excel file data. current workbook end point url as follows(which is not working):
`var workbookEndpoint = "https://graph.microsoft.com/beta/sites/mydomain.sharepoint.com:/foa/bd:/lists/Budget/items/" + fileId + "/workbook";`

my complete method to update cell value in excel file on sharepoint as follows:

` public static async Task UpdateExcelCellValue_Sharepoint(string accessToken, string cellAddress, string val)
        {
            string worksheetName = "Parameters";
            var serviceEndpoint = "https://graph.microsoft.com/beta/sites/mydomain.sharepoint.com:/foa/bd:/lists/Budget/items";
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var filesResponse = await client.GetAsync(serviceEndpoint + "?$select=name,id");
            if (filesResponse.IsSuccessStatusCode)
            {
                var filesContent = await filesResponse.Content.ReadAsStringAsync();
                JObject parsedResult = JObject.Parse(filesContent);
                foreach (JObject file in parsedResult["value"])
                {
                    var name = (string)file["id"];
                    if (name.Contains("173"))
                    {
                        fileId = (string)file["id"];
                        break;
                    }
                }
            }
            else
            {
                //Handle failed response
            }
            //Set up workbook and worksheet endpoints
            var workbookEndpoint = "https://graph.microsoft.com/beta/sites/mydomain.sharepoint.com:/foa/bd:/lists/Budget/items/" + fileId + "/workbook";
            var worksheetsEndpoint = workbookEndpoint + "/worksheets";
            var patchMethod = new HttpMethod("PATCH");
            var summaryTableRowJson = "{" +
                    "'values': '" + val + ".csv'" +
                "}";
            var colNamePatchBody = new StringContent(summaryTableRowJson);
            colNamePatchBody.Headers.Clear();
            colNamePatchBody.Headers.Add("Content-Type", "application/json");
            var colNameRequestMessage = new HttpRequestMessage(patchMethod, worksheetsEndpoint +
                "('" + worksheetName + "')/range(address='Parameters!B2')")
            { Content = colNamePatchBody };
            var colNameResponseMessage = await client.SendAsync(colNameRequestMessage);
        }`
any help would be highly appreciated.

**Comment by jamescro** [comment]
Thanks for your question. I'm following up on this to see how you can reach a workbook in SharePoint. Have you asked this on StackOverflow?

**Comment by ravianand1988** [comment]
Yes sir,  I did. here is link https://stackoverflow.com/questions/45715200/work-with-excel-file-using-sharepoint-document-library-with-microsoft-graph-api

**Comment by jamescro** [comment]
Thanks! We'll want to make sure that the answer gets captured there as well.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp for an ASP.NET sample.
