### ISSUE TITLE
Excel "functions" vs. Rest API "functions" documentation

### ISSUE THREAD

**Issue by mgd** [microsoftgraph/aspnet-todo-rest-sample#8]
It is stated that only only excel functions work in MS graph. However, 
 the Graph/Rest Api has extends its ability in that you can select/copy objects (https://docs.microsoft.com/en-us/graph/excel-write-to-workbook) 

Where can I find all the available "abilites" or "functionality" of Graph/Rest API? I have spent ~an hr searching for a list, but am only able to find scatered functionality like selecting a cell or range (https://stackoverflow.com/questions/45782087/sharepoint-2013-rest-api-call-to-extract-excel-specific-cells?rq=1 )

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp for an ASP.NET sample.
